export const SET_FILES = 'SET_FILES'
export const SET_ROWS = 'SET_ROWS'
export const SET_ERROR = 'SET_ERROR'
export const SET_USERS = 'SET_USERS'
export const CLEAR_USERS = 'CLEAR_USERS'
export const DELETE_USER = 'DELETE_USER'
export const SET_RESULT = 'SET_RESULT'